import type {
  AdminOverview,
  AdminUser,
  AvailabilitySlot,
  Canoe,
  Customer,
  Expedition,
  Experience,
  MemberDashboard,
  Participant,
  Payment,
  Reservation,
  TermVersion,
} from "@/domain/types";
import { buildReservationQuote } from "@/domain/rules";

export const experiences: Experience[] = [
  {
    id: "exp_nascer_sol",
    slug: "nascer-do-sol",
    name: "Nascer do Sol",
    kind: "regular",
    shortDescription: "Remada ao amanhecer com visual calmo e ritmo contemplativo.",
    description: "Uma experiência especial para ver Ilhéus acordando pelo mar, com orientação da equipe e rota segura.",
    priceCents: 5000,
    currency: "BRL",
    durationMinutes: 150,
    scheduleLabel: "04:30 às 07:00",
    minParticipants: 4,
    maxParticipants: 25,
    meetingPoint: "Praia do Cristo, Ilhéus",
    difficulty: "iniciante",
    quotaCost: 2,
    imageClass: "canoe-sunrise",
    availableTimes: ["04:30"],
    includedItems: ["Colete", "Remo", "Instrução", "Guia experiente"],
    guidance: ["Chegue 20 minutos antes", "Use roupa leve", "Leve água e protetor solar"],
    safetyNotes: ["Atividade depende das condições do mar", "Coletes são obrigatórios"],
    galleryImages: [
      {
        id: "nascer_do_sol_01",
        src: "/experiences/nascer-do-sol-01.jpg",
        alt: "Canoa havaiana no mar durante o nascer do sol em Ilhéus",
        caption: "Primeira luz no litoral de Ilhéus",
        objectPosition: "center 58%",
      },
      {
        id: "nascer_do_sol_02",
        src: "/experiences/nascer-do-sol-02.jpg",
        alt: "Pessoa remando com o sol nascendo refletindo no mar",
        caption: "Remada leve com o dia amanhecendo",
        objectPosition: "center 42%",
      },
      {
        id: "nascer_do_sol_03",
        src: "/experiences/nascer-do-sol-03.jpg",
        alt: "Grupo em canoas havaianas celebrando o nascer do sol",
        caption: "Grupo reunido para receber o dia no mar",
        objectPosition: "center 48%",
      },
    ],
    isActive: true,
  },
  {
    id: "exp_remada_avulsa",
    slug: "remada-avulsa",
    name: "Remada Avulsa",
    kind: "regular",
    shortDescription: "Uma remada prática para conhecer a canoa havaiana.",
    description: "Opçao direta para quem quer conhecer o remo com instruçaoo e acompanhamento.",
    priceCents: 3500,
    currency: "BRL",
    durationMinutes: 75,
    scheduleLabel: "Horários variados",
    minParticipants: 4,
    maxParticipants: 25,
    meetingPoint: "Praia do Cristo, Ilhéus",
    difficulty: "iniciante",
    quotaCost: 1,
    imageClass: "canoe-coast",
    availableTimes: ["06:00", "07:30", "16:00"],
    includedItems: ["Colete", "Remo", "Instrução"],
    guidance: ["Chegue 15 minutos antes", "Evite objetos soltos"],
    safetyNotes: ["Atividade sujeita a avaliação climática"],
    galleryImages: [
       {
        id: "remada_avulsa_01",
        src: "/experiences/avulso.png",
        alt: "Tenha experiência de remada em canoa havaiana em Ilhéus com amigos",
        caption: "Reme com amigos e explore a costa de Ilhéus",
        objectPosition: "center 50%",
      },
    ],
    isActive: true,
  },
  {
    id: "exp_por_do_sol",
    slug: "por-do-sol",
    name: "Pôr do Sol",
    kind: "regular",
    shortDescription: "Remada no fim da tarde com chegada em luz dourada.",
    description: "Explore as praias e encostas de Ilhéus em uma rota leve e fotogênica no fim do dia.",
    priceCents: 3500,
    currency: "BRL",
    durationMinutes: 90,
    scheduleLabel: "16:30 às 18:00",
    minParticipants: 4,
    maxParticipants: 25,
    meetingPoint: "Praia do Cristo, Ilhéus",
    difficulty: "iniciante",
    quotaCost: 1,
    imageClass: "canoe-coast",
    availableTimes: ["16:30"],
    includedItems: ["Colete", "Remo", "Monitoramento de clima", "Guia experiente"],
    guidance: ["Chegue 20 minutos antes", "Leve uma troca seca"],
    safetyNotes: ["A rota pode mudar conforme vento e maré"],
    galleryImages: [],
    isActive: true,
  },
  {
    id: "exp_lua_cheia",
    slug: "lua-cheia",
    name: "Lua Cheia",
    kind: "regular",
    shortDescription: "Remada noturna em datas especiais de lua cheia.",
    description: "Experiência disponível apenas em datas específicas, com confirmação prévia da equipe.",
    priceCents: 3500,
    currency: "BRL",
    durationMinutes: 90,
    scheduleLabel: "Datas específicas",
    minParticipants: 4,
    maxParticipants: 25,
    meetingPoint: "Praia do Cristo, Ilhéus",
    difficulty: "intermediario",
    quotaCost: 1,
    imageClass: "canoe-sunrise",
    availableTimes: ["18:30"],
    includedItems: ["Colete", "Remo", "Luzes de segurança", "Guia experiente"],
    guidance: ["Confirmação depende do calendário lunar", "Use roupa clara"],
    safetyNotes: ["Atividade confirmada somente com mar seguro"],
    galleryImages: [
      {
        id: "lua_cheia_01",
        src: "/experiences/luacheia01.png",
        alt: "Canoa havaiana em remada de lua cheia em Ilhéus",
        caption: "Remada especial em noite de lua cheia",
        objectPosition: "center 52%",
      },
    ],
    isActive: true,
  },
  {
    id: "exp_comemoracoes",
    slug: "comemoracoes",
    name: "Comemorações",
    kind: "celebration",
    shortDescription: "Reserva especial para aniversários, grupos e celebrações.",
    description: "Monte uma remada personalizada para grupos, com mínimo de 6 participantes.",
    priceCents: 5000,
    currency: "BRL",
    durationMinutes: 120,
    scheduleLabel: "Sob consulta",
    minParticipants: 6,
    maxParticipants: 25,
    meetingPoint: "Praia do Cristo, Ilhéus",
    difficulty: "iniciante",
    quotaCost: 2,
    imageClass: "canoe-coast",
    availableTimes: ["07:30", "16:30"],
    includedItems: ["Colete", "Remo", "Instrução", "Apoio de equipe"],
    guidance: ["Informe o tipo de comemoração", "Chegue 30 minutos antes"],
    safetyNotes: ["Capacidade depende das canoas disponíveis"],
    galleryImages: [],
    isActive: true,
  },
  {
    id: "exp_expedicoes",
    slug: "expedicoes",
    name: "Expedições",
    kind: "expedition",
    shortDescription: "Rotas especiais a partir de R$ 50 por pessoa.",
    description: "Experiências mais longas para destinos como Pedra de Ilhéus, Rio do Engenho e Parque Marinho.",
    priceCents: 5000,
    currency: "BRL",
    durationMinutes: 180,
    scheduleLabel: "Sob agenda",
    minParticipants: 4,
    maxParticipants: 25,
    meetingPoint: "Definido conforme destino",
    difficulty: "intermediario",
    quotaCost: 2,
    imageClass: "canoe-sunrise",
    availableTimes: ["06:00"],
    includedItems: ["Colete", "Remo", "Planejamento de rota", "Guia experiente"],
    guidance: ["Destino confirmado pela administração", "Exige avaliação climática"],
    safetyNotes: ["Pode ser remarcada por segurança operacional"],
    galleryImages: [
      {
        id: "expedicao_01",
        src: "/experiences/expedicao.jpg",
        alt: "Canoa havaiana em expedição rumo à Pedra de Ilhéus",
        caption: "Rota especial para destinos costeiros",
        objectPosition: "center 52%",
      },
      {
        id: "expedicao_02",
        src: "/experiences/expedicao02.jpg",
        alt: "Grupo em canoa havaiana durante uma expedição em Ilhéus",
        caption: "Expedições planejadas conforme clima e maré",
        objectPosition: "center 50%",
      },
    ],
    isActive: true,
  },
];

export const expeditions: Expedition[] = [
  {
    id: "dest_pedra_ilheus",
    slug: "pedra-de-ilheus",
    name: "Pedra de Ilhéus",
    destination: "Pedra de Ilhéus",
    description: "Expedição costeira com destino icônico da região.",
    startingPriceCents: 5000,
    minParticipants: 4,
    maxParticipants: 25,
    isActive: true,
  },
  {
    id: "dest_rio_engenho",
    slug: "rio-do-engenho",
    name: "Rio do Engenho",
    destination: "Rio do Engenho",
    description: "Rota em águas abrigadas para grupos e experiências culturais.",
    startingPriceCents: 5000,
    minParticipants: 4,
    maxParticipants: 25,
    isActive: true,
  },
  {
    id: "dest_parque_marinho",
    slug: "parque-marinho",
    name: "Parque Marinho",
    destination: "Parque Marinho",
    description: "Expedição planejada para dias de mar favorável.",
    startingPriceCents: 5000,
    minParticipants: 4,
    maxParticipants: 25,
    isActive: true,
  },
];

export const canoes: Canoe[] = [
  { id: "canoe_1", name: "Canoa 1", capacity: 5, status: "available" },
  { id: "canoe_2", name: "Canoa 2", capacity: 5, status: "available" },
  { id: "canoe_3", name: "Canoa 3", capacity: 5, status: "available" },
  { id: "canoe_4", name: "Canoa 4", capacity: 5, status: "available" },
  { id: "canoe_5", name: "Canoa 5", capacity: 5, status: "maintenance" },
];

export const availabilitySlots: AvailabilitySlot[] = [
  { id: "slot_1", experienceSlug: "nascer-do-sol", date: "2026-08-10", time: "04:30", capacityTotal: 20, booked: 12, availableSpots: 8, status: "available" },
  { id: "slot_2", experienceSlug: "remada-avulsa", date: "2026-08-11", time: "07:30", capacityTotal: 20, booked: 17, availableSpots: 3, status: "low" },
  { id: "slot_3", experienceSlug: "por-do-sol", date: "2026-08-12", time: "16:30", capacityTotal: 20, booked: 8, availableSpots: 12, status: "available" },
  { id: "slot_4", experienceSlug: "lua-cheia", date: "2026-08-14", time: "18:30", capacityTotal: 20, booked: 20, availableSpots: 0, status: "full" },
  { id: "slot_5", experienceSlug: "comemoracoes", date: "2026-08-15", time: "16:30", capacityTotal: 20, booked: 0, availableSpots: 20, status: "available" },
];

export const activeTerm: TermVersion = {
  id: "term_risk_2026_01",
  name: "Termo de Ciencia de Riscos e Responsabilidade",
  version: "2026.1",
  content: "Declaro ciência dos riscos inerentes à atividade náutica e aceito seguir as orientações da equipe.",
  effectiveFrom: "2026-01-01",
  status: "active",
};

export const sampleCustomer: Customer = {
  fullName: "Fabio Almeida",
  cpf: "000.000.000-00",
  birthDate: "1990-05-20",
  phone: "(73) 99999-0000",
  email: "fabio@email.com",
  address: "Rua da Praia, 120 - Ilhéus, BA",
  willParticipate: true,
};

export const sampleParticipants: Participant[] = [
  {
    id: "participant_1",
    fullName: "Fabio Almeida",
    cpf: "000.000.000-00",
    birthDate: "1990-05-20",
    phone: "(73) 99999-0000",
    emergencyContactName: "Marina Almeida",
    emergencyContactPhone: "(73) 98888-0000",
    termsAccepted: true,
  },
  {
    id: "participant_2",
    fullName: "Ana Oliveira",
    cpf: "111.111.111-11",
    birthDate: "1992-03-10",
    phone: "(73) 97777-0000",
    emergencyContactName: "Carlos Oliveira",
    emergencyContactPhone: "(73) 96666-0000",
    termsAccepted: true,
  },
  {
    id: "participant_3",
    fullName: "Renato Cunha",
    cpf: "222.222.222-22",
    birthDate: "1988-08-15",
    phone: "(73) 95555-0000",
    emergencyContactName: "Lia Cunha",
    emergencyContactPhone: "(73) 94444-0000",
    termsAccepted: true,
  },
  {
    id: "participant_4",
    fullName: "Bruna Santos",
    cpf: "333.333.333-33",
    birthDate: "1995-11-02",
    phone: "(73) 93333-0000",
    emergencyContactName: "Paulo Santos",
    emergencyContactPhone: "(73) 92222-0000",
    termsAccepted: true,
  },
];

const porDoSol = experiences.find((experience) => experience.slug === "por-do-sol") ?? experiences[0];
const nascerDoSol = experiences.find((experience) => experience.slug === "nascer-do-sol") ?? experiences[0];

const waitingPayment: Payment = {
  id: "pay_3108",
  method: "pix",
  status: "waiting_payment",
  amountCents: 14000,
  dueAt: "2026-08-10T16:30:00.000Z",
  pixCopyPaste: "00020101021226880014br.gov.bcb.pix.mock",
};

export const reservations: Reservation[] = [
  {
    id: "reservation_3108",
    code: "ICV-3108",
    experienceSlug: porDoSol.slug,
    experienceName: porDoSol.name,
    date: "2026-08-12",
    time: "16:30",
    participantsCount: 4,
    customer: sampleCustomer,
    participants: sampleParticipants,
    quote: buildReservationQuote(porDoSol, 4),
    payment: waitingPayment,
    status: "waiting_payment",
    createdAt: "2026-08-09T10:00:00.000Z",
  },
  {
    id: "reservation_2408",
    code: "ICV-2408",
    experienceSlug: nascerDoSol.slug,
    experienceName: nascerDoSol.name,
    date: "2026-08-10",
    time: "04:30",
    participantsCount: 4,
    customer: sampleCustomer,
    participants: sampleParticipants,
    quote: buildReservationQuote(nascerDoSol, 4),
    payment: { id: "pay_2408", method: "pix", status: "confirmed", amountCents: 20000, dueAt: "2026-08-08T04:30:00.000Z" },
    status: "confirmed",
    createdAt: "2026-08-07T12:00:00.000Z",
  },
];

export const adminUsers: AdminUser[] = [
  { id: "admin_1", name: "Marina Costa", role: "admin", permissions: { reservations: true, finance: true, members: true } },
  { id: "admin_2", name: "Caio Santos", role: "instructor", permissions: { reservations: true, finance: false, members: false } },
  { id: "admin_3", name: "Lia Menezes", role: "support", permissions: { reservations: true, finance: false, members: true } },
];

export const memberDashboard: MemberDashboard = {
  member: {
    id: "member_1",
    name: "Fabio",
    status: "active",
    invoiceDueDate: "2026-11-15",
    nextRenewalLabel: "segunda-feira",
  },
  plan: {
    id: "plan_aloha",
    name: "Plano Aloha",
    monthlyPriceCents: 15000,
    weeklyQuota: 3,
    quotasAccumulate: false,
  },
  quotasAvailable: 3,
  quotaMovements: [
    { id: "quota_1", date: "2026-08-03", type: "renewal", quantity: 3, previousBalance: 0, nextBalance: 3, description: "Renovação semanal" },
    { id: "quota_2", date: "2026-08-07", type: "reservation_use", quantity: -1, reservationCode: "ICV-1821", previousBalance: 3, nextBalance: 2, description: "Pôr do Sol" },
    { id: "quota_3", date: "2026-08-08", type: "manual_adjustment", quantity: 1, previousBalance: 2, nextBalance: 3, description: "Ajuste administrativo" },
  ],
  nextReservation: reservations[1],
};

export const adminOverview: AdminOverview = {
  reservationsToday: 2,
  participantsToday: 8,
  availableSpotsToday: 12,
  confirmedRevenueCents: 20000,
  pendingPayments: 1,
  activeMembers: 14,
  confirmations: reservations,
  users: adminUsers,
};
